Convert feature test to system tests
umts/jobapps pull request #403
Opened 2021-01-12 19:48 UTC by Tanvish

Should close #388 
- Mostly included all the information in the commit messages but there aren't any major changes per say.

2021-01-13 14:48 UTC, Anbranin commented on Gemfile
> +  gem 'vcr'
Do we need this gem? Where are we using it?

2021-01-13 19:15 UTC, Anbranin requested changes

2021-01-14 17:19 UTC, werebus requested changes

2021-01-14 17:19 UTC, werebus commented on Gemfile
> +  gem 'selenium-webdriver'
Karin should have specified, but you should have only `webdrivers` in here.

`webdrivers` depends on `selenium-webdriver`, but also does some helpful, "download the correct version and tell selenium to use it" work for us.

2021-01-14 17:19 UTC, werebus commented on Gemfile
> +  gem 'selenium-webdriver'
Also, don't forget to bundle and commit the `Gemfile.lock` when changing the `Gemfile`.

2021-01-14 18:33 UTC, Tanvish commented on Gemfile
> +  gem 'selenium-webdriver'
Yeah, I wasn't sure but good to know and I forgot to bundle sorry!

2021-01-15 16:06 UTC, werebus approved these changes

2021-01-15 17:43 UTC, Anbranin approved these changes

2021-01-19 15:37 UTC, merged