Remove datepickers on the actual job applications
umts/jobapps pull request #539
Opened 2024-01-18 04:55 UTC by werebus

Second (of three) part to #484

2024-01-18 16:36 UTC, dirschn requested changes
Logging in as Justin and viewing "my" application gives me 
![image](https://github.com/umts/jobapps/assets/25785789/ce625b4c-94c5-4acc-8aaf-36a0e1406db3)

2024-01-18 16:36 UTC, dirschn commented on app/views/application_submissions/show.haml
> +        %td=format_response response, data_type
```suggestion
        %td= format_response response, data_type
```

2024-01-18 16:41 UTC, werebus commented
> Logging in as Justin and viewing "my" application gives me ...

Did you run the rake task?

2024-01-18 16:41 UTC, dirschn commented
> Did you run the rake task?

Absolutely not I didn't

2024-01-18 16:54 UTC, dirschn requested changes
sorry missed this before

2024-01-19 15:15 UTC, dirschn approved these changes

2024-01-19 15:41 UTC, merged